from fpdf import FPDF


def generate_report(
    age,
    credit_amount,
    month_duration,
    probability,
    credit_score,
    prediction_text
):

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # =====================
    # LOGO
    # =====================

    pdf.image(
        "assets/themis_logo.png",
        x=75,
        y=10,
        w=60
    )

    pdf.ln(65)

    # =====================
    # TITLE
    # =====================

    pdf.set_text_color(16, 47, 94)

    pdf.set_font("Times", "B", 24)

    pdf.cell(
        0,
        10,
        "THEMIS CREDIT RISK ASSESSMENT REPORT",
        ln=True,
        align="C"
    )

    pdf.set_font("Times", "", 14)

    pdf.set_text_color(201, 161, 93)

    pdf.cell(
        0,
        10,
        "AI-Powered Credit Risk Intelligence Platform",
        ln=True,
        align="C"
    )

    pdf.ln(5)

    pdf.set_draw_color(201, 161, 93)

    pdf.line(
        20,
        pdf.get_y(),
        190,
        pdf.get_y()
    )

    pdf.ln(10)

    # =====================
    # EXECUTIVE SUMMARY
    # =====================

    pdf.set_text_color(16, 47, 94)

    pdf.set_font("Times", "B", 18)

    pdf.cell(
        0,
        10,
        "Executive Summary",
        ln=True
    )

    pdf.set_font("Helvetica", "", 11)

    pdf.set_text_color(0, 0, 0)

    pdf.multi_cell(
        0,
        8,
        "This report has been generated by the THEMIS Credit Risk Intelligence Platform. "
        "The applicant was evaluated using machine learning driven credit risk modelling "
        "techniques that analyze demographic, financial, employment and credit behavior "
        "characteristics."
    )

    pdf.ln(4)

    # =====================
    # APPLICANT PROFILE
    # =====================

    pdf.set_font("Times", "B", 18)

    pdf.set_text_color(16, 47, 94)

    pdf.cell(
        0,
        10,
        "Applicant Profile",
        ln=True
    )

    pdf.set_font("Helvetica", "", 12)

    pdf.set_text_color(0, 0, 0)

    pdf.cell(
        0,
        8,
        f"Applicant Age: {age}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Requested Credit Amount: ${credit_amount:,.0f}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Loan Duration: {month_duration} Months",
        ln=True
    )

    pdf.ln(4)

    # =====================
    # CREDIT RISK METRICS
    # =====================

    pdf.set_font("Times", "B", 18)

    pdf.set_text_color(16, 47, 94)

    pdf.cell(
        0,
        10,
        "Credit Risk Metrics",
        ln=True
    )

    pdf.set_font("Helvetica", "", 12)

    pdf.set_text_color(0, 0, 0)

    pdf.cell(
        0,
        8,
        f"Approval Probability: {probability:.2%}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Credit Score: {credit_score}",
        ln=True
    )

    pdf.cell(
        0,
        8,
        f"Model Prediction: {prediction_text}",
        ln=True
    )

    pdf.ln(4)

    # =====================
    # RISK CLASSIFICATION
    # =====================

    if probability >= 0.80:
        risk_level = "LOW RISK"
        r, g, b = (0, 120, 0)

    elif probability >= 0.60:
        risk_level = "MEDIUM RISK"
        r, g, b = (201, 161, 93)

    else:
        risk_level = "HIGH RISK"
        r, g, b = (180, 0, 0)

    pdf.set_font("Times", "B", 18)

    pdf.set_text_color(16, 47, 94)

    pdf.cell(
        0,
        10,
        "Risk Classification",
        ln=True
    )

    pdf.set_fill_color(r, g, b)

    pdf.set_text_color(255, 255, 255)

    pdf.set_font("Helvetica", "B", 16)

    pdf.cell(
        80,
        12,
        risk_level,
        ln=True,
        align="C",
        fill=True
    )

    pdf.ln(5)

    # =====================
    # AI INTERPRETATION
    # =====================

    pdf.set_font("Times", "B", 18)

    pdf.set_text_color(16, 47, 94)

    pdf.cell(
        0,
        10,
        "AI Interpretation",
        ln=True
    )

    pdf.set_font("Helvetica", "", 11)

    pdf.set_text_color(0, 0, 0)

    pdf.multi_cell(
        0,
        8,
        f"""
The applicant achieved a credit score of {credit_score}
with an estimated repayment probability of {probability:.2%}.

The machine learning model classified this application
as '{prediction_text}'.

The evaluation indicates the applicant's overall
creditworthiness based on repayment behavior,
financial stability and historical credit patterns.

This report should be used as a decision-support
tool alongside underwriting and compliance review.
"""
    )

    pdf.ln(5)

    # =====================
    # FOOTER
    # =====================

    pdf.set_y(-20)

    pdf.set_draw_color(201, 161, 93)

    pdf.line(
        20,
        pdf.get_y(),
        190,
        pdf.get_y()
    )

    pdf.ln(5)

    pdf.set_font("Helvetica", "I", 9)

    pdf.cell(
        0,
        5,
        "THEMIS Credit Risk Intelligence | Confidential Report",
        align="C"
    )

    filename = "THEMIS_Credit_Report.pdf"

    pdf.output(filename)

    return filename

